### ISSUE TITLE
Persistence API for event handlers

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#126]
Event sourced actors should also be able to persist new event during event handling directly, not only during command handling. This can be layered on top of at-least-once message delivery to self to achieve exactly-once-processing semantics.

**Comment by morsch** [comment]
Using at-least-once delivery requires a message id that's derived on the *consume* side (where the at-least-once delivery is initiated) and available on the *emission* side (where the at-least-once delivery is confirmed).

In general, the message id can easily be generated or derived (counter or sequence id) on the consume side, and persisted alongside the emitted event so that it is available on the emission side. 

Sometimes the same unique id can be derived from the "payload" data in both contexts. In those cases it's unnecessary overhead to store the message id alongside the emitted event.

**Comment by krasserm** [comment]
Good point @morsch, will include it into the design considerations.

**Comment by volkerstampa** [comment]
For the use-case that an event-sourced actor emits events on reception of another event, it would be great if an event-sourced actor could be such a processor. API-wise its `onEvent` could either return these _new_ events or emit them through a method like `persist`

**Comment by krasserm** [comment]
@volkerstampa makes absolutely sense. `EventsourcedActor` will be be extended to have that API.

**Comment by krasserm** [comment]
If there are multiple replicas of an `EventsourcedActor` it is important that only one of these replicas may actually emit a new event on receiving a given event.
