### ISSUE TITLE
Topic-based event routing

### ISSUE THREAD

**Issue by krasserm** [RBMHTechnology/eventuate#46]
#45 introduces basic routing capabilities. This should be extended to allow

- producers to publish events to application-defined topics and
- consumers to consume events from application-defined topics

Topic-based event routing **must** preserve causality of events and should be possible for event routing between actors that share a single, distributed log. Routing across different logs can be done with [processors](http://rbmhtechnology.github.io/eventuate/architecture.html#event-sourced-processors).

Furthermore, it should be investigated if routing decisions must be made persistent, so that past routings are repeatable. On the other hand, a changed routing rule is somewhat equivalent to changed event handler logic which isn't persistent either. 

#130 could be used as implementation basis.

**Comment by krasserm** [comment]
Topic based event communication can lead to large vector clock sizes if many event-sourced actors subscribe and publish to a given topic. #68 is one possible solution to this problem.

**Comment by drozzy** [comment]
This is really beautiful, and what I really wanted from Akka PA's. Implements the  "Event storage as a queue" nicely https://cqrs.wordpress.com/documents/building-event-storage/

**Comment by VaughnVernon** [comment]
(1) I would like to suggest that you make None an opt-out from all routing and replica rules. This seems like a natural design choice rather than to say that all actors with a None aggregateId route to each other. I assumed that since aggregateId was declared as Option[String], that None must have a logical meaning that is opt-out.

(2) I would also like to suggest that you rename aggregateId to routeId so that it is not confused with DDD aggregate, which I don't think it really is anything like. DDD aggreate is about transactional consistency, and no two actors can have transactional consistency. I do agree that this is a worthwhile routing innovation for actors. Hence, routeId.

**Comment by krasserm** [comment]
@VaughnVernon thanks for your useful comments. I plan to unify routing into *topic-based routing* as described in the [initial comment](#issue-59755422). This will make `aggregateId`, `routeId` or whatever a *topic* and an actor can subscribe to and publish to zero or more topics. A subscription to zero topics would then correspond to the semantics you proposed for an `aggregateId` of value `None`.

Regarding the consistency of a DDD aggregate, I understand that literature is usually talking about strong consistency in this case which makes sense for many applications. On the other hand, there are also applications that require higher availability of a DDD aggregate (i.e. want to have AP from CAP)
 with consistency relaxed to [causal consistency](https://en.wikipedia.org/wiki/Causal_consistency). In my opinion, it's still an aggregate but a replicated one with write-availability on multiple masters. In both cases, the semantics are clearly defined: total event order vs. causal event order.

**Comment by krasserm** [comment]
Won't implement for reasons explained in https://github.com/RBMHTechnology/eventuate/issues/130#issuecomment-173873665
