### ISSUE TITLE
Infinite loop in BatchingEventLog

### ISSUE THREAD

**Issue by maekl** [RBMHTechnology/eventuate#63]
`writeAll()` gets stuck in an infinite loop if the number of events in a `Write` is larger than the maximum batch size.

**Comment by maekl** [comment]
I might have a fix, https://github.com/maekl/eventuate/commit/8a570c6e3fe3b6b3d175865e3d3a1c2090ca7594, but I'm not sure if it is OK to split Writes like it does.

**Comment by krasserm** [comment]
Good catch @maekl. Your solution proposal goes into the right direction but I think it's better not to split `Write`s coming from `EventsourcedProcessor`s (for batch-write atomicity reasons: all events `persist`ed per command should be written atomically). If a `Write` is larger than `batchSizeLimit` we should send that `Write`. Checking the `batch` head as you did is necessary: if it is larger than `batchSizeLimit` send that `Write` only, otherwise append further `Write`s. This should also be clarified in documentation of the `batch-size-max` configuration in `reference.conf`. WDYT?

**Comment by maekl** [comment]
Thanks. Makes perfect sense. I created a PR https://github.com/RBMHTechnology/eventuate/pull/64 which will just write the `Write`
